In [1]:
import tensorflow as tf

In [3]:


a = tf.constant(3.0, dtype=tf.float32)
b = tf.constant(4.0) # also tf.float32 implicitly
total = a + b
print(a)
print(b)
print(total)

Tensor("Const:0", shape=(), dtype=float32)
Tensor("Const_1:0", shape=(), dtype=float32)
Tensor("add:0", shape=(), dtype=float32)


In [4]:
who

a	 b	 tf	 total	 


In [23]:
writer = tf.summary.FileWriter('.')
writer.add_graph(tf.get_default_graph())

In [7]:
who

a	 b	 tf	 total	 writer	 


In [10]:
sess = tf.Session( )
print (   sess.run ( total ))

7.0


In [11]:
print( sess.run ({'total':total, 'ab': (a, b)}  ))

{'total': 7.0, 'ab': (3.0, 4.0)}


In [16]:
vec = tf.random_uniform(shape = (2, ))
out1 = vec+1; out2 = vec+2
print(sess.run(( vec, vec) ))
print( sess.run (  (out1, out2)  ))

(array([0.36314297, 0.7894875 ], dtype=float32), array([0.36314297, 0.7894875 ], dtype=float32))
(array([1.0750918, 1.8443893], dtype=float32), array([2.0750918, 2.8443894], dtype=float32))


In [19]:
a = sess.run(vec); 
type(a )

numpy.ndarray

In [20]:
x = tf.placeholder(tf.float32); y = tf.placeholder(tf.float32)
z = x+y 

In [24]:
print( sess.run( z, feed_dict={x:(1,2), y:3}))

[4. 5.]


In [25]:
my_data = [
    [0, 1,],
    [2, 3,],
    [4, 5,],
    [6, 7,],
]
slices = tf.data.Dataset.from_tensor_slices(my_data)
next_item = slices.make_one_shot_iterator().get_next()

In [29]:
while True:
    try: 
        print( sess.run( next_item ))
    except tf.errors.OutOfRangeError:
        break
    

[2 3]
[4 5]
[6 7]


In [30]:
print(sess.run(next_item))

OutOfRangeError: End of sequence
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[2]], output_types=[DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]

Caused by op 'IteratorGetNext', defined at:
  File "/Users/anbian/anaconda3/envs/tf-pytorch/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/anbian/anaconda3/envs/tf-pytorch/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/anbian/anaconda3/envs/tf-pytorch/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/Users/anbian/anaconda3/envs/tf-pytorch/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/anbian/anaconda3/envs/tf-pytorch/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 486, in start
    self.io_loop.start()
  File "/Users/anbian/anaconda3/envs/tf-pytorch/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 127, in start
    self.asyncio_loop.run_forever()
  File "/Users/anbian/anaconda3/envs/tf-pytorch/lib/python3.6/asyncio/base_events.py", line 422, in run_forever
    self._run_once()
  File "/Users/anbian/anaconda3/envs/tf-pytorch/lib/python3.6/asyncio/base_events.py", line 1432, in _run_once
    handle._run()
  File "/Users/anbian/anaconda3/envs/tf-pytorch/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/Users/anbian/anaconda3/envs/tf-pytorch/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 117, in _handle_events
    handler_func(fileobj, events)
  File "/Users/anbian/anaconda3/envs/tf-pytorch/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/anbian/anaconda3/envs/tf-pytorch/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "/Users/anbian/anaconda3/envs/tf-pytorch/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/anbian/anaconda3/envs/tf-pytorch/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/Users/anbian/anaconda3/envs/tf-pytorch/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/anbian/anaconda3/envs/tf-pytorch/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/Users/anbian/anaconda3/envs/tf-pytorch/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/Users/anbian/anaconda3/envs/tf-pytorch/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/Users/anbian/anaconda3/envs/tf-pytorch/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/anbian/anaconda3/envs/tf-pytorch/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/Users/anbian/anaconda3/envs/tf-pytorch/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/Users/anbian/anaconda3/envs/tf-pytorch/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Users/anbian/anaconda3/envs/tf-pytorch/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2903, in run_ast_nodes
    if self.run_code(code, result):
  File "/Users/anbian/anaconda3/envs/tf-pytorch/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-25-2e707051fb48>", line 8, in <module>
    next_item = slices.make_one_shot_iterator().get_next()
  File "/Users/anbian/anaconda3/envs/tf-pytorch/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 370, in get_next
    name=name)), self._output_types,
  File "/Users/anbian/anaconda3/envs/tf-pytorch/lib/python3.6/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 1466, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/Users/anbian/anaconda3/envs/tf-pytorch/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/anbian/anaconda3/envs/tf-pytorch/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/Users/anbian/anaconda3/envs/tf-pytorch/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

OutOfRangeError (see above for traceback): End of sequence
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[2]], output_types=[DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]


In [32]:
r = tf.random_normal([10,3])
dataset = tf.data.Dataset.from_tensor_slices(r)
iterator = dataset.make_initializable_iterator()
next_row = iterator.get_next()

sess.run(iterator.initializer)
while True:
  try:
    print(sess.run(next_row))
  except tf.errors.OutOfRangeError:
    break

[ 2.09717    -0.05076594 -0.8667728 ]
[ 1.2309282   0.21447052 -0.73225   ]
[-1.1604847  -1.4559518   0.29128674]
[ 0.60393405  0.8026485  -1.4943483 ]
[ 0.96757275 -0.2353452  -0.5346115 ]
[-1.8994635  -0.19786216 -0.29960102]
[ 0.72692275 -0.7340344  -0.88664496]
[-1.863734    0.26796764 -0.3242746 ]
[-0.17958489 -0.53184944 -0.31124118]
[ 0.14874306  0.77289706 -1.2018588 ]


In [33]:
iterator.initializer

<tf.Operation 'MakeIterator_1' type=MakeIterator>

In [34]:
x = tf.placeholder(tf.float32, shape=[None, 3])
linear_model = tf.layers.Dense(units=1)
y = linear_model(x)

In [40]:
init = tf.global_variables_initializer()
sess.run(init)
type(init)

tensorflow.python.framework.ops.Operation

In [39]:
import numpy as np
print(sess.run ( y, feed_dict= {x: np.ones( [1,3]) }))

[[0.12116361]]


In [48]:
features = {
    'sales' : [[5], [10], [8], [9]],
    'department': ['sports', 'sports', 'gardening', 'gardening']}

department_column = tf.feature_column.categorical_column_with_vocabulary_list(
        'department', ['sports', 'gardening'])
department_column = tf.feature_column.indicator_column(department_column)

col1 = tf.feature_column.numeric_column('sales')
columns = [
    tf.feature_column.numeric_column('sales'),
    department_column
]


inputs = tf.feature_column.input_layer(features, columns)

In [50]:
inputs.shape

TensorShape([Dimension(4), Dimension(3)])

In [51]:
var_init = tf.global_variables_initializer()
table_init = tf.tables_initializer()
sess = tf.Session()
sess.run((var_init, table_init))

(None, None)

In [52]:
print(sess.run (inputs)  )

[[ 1.  0.  5.]
 [ 1.  0. 10.]
 [ 0.  1.  8.]
 [ 0.  1.  9.]]


## train a regression model

In [53]:
x = tf.constant([[1], [2], [3], [4]], dtype=tf.float32)
y_true = tf.constant([[0], [-1], [-2], [-3]], dtype=tf.float32)

In [54]:
linear_m = tf.layers.Dense(units=1)
y = linear_m(x)

In [56]:
sess=tf.Session()
init = tf.global_variables_initializer()
sess.run(init)


In [57]:
sess.run( y )

array([[0.43047917],
       [0.86095834],
       [1.2914375 ],
       [1.7219167 ]], dtype=float32)

In [58]:

loss = tf.losses.mean_squared_error(labels=y_true, predictions=y)

In [59]:
sess.run(loss)

9.194634

In [60]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.02)
train = optimizer.minimize(loss)

In [61]:
train

<tf.Operation 'GradientDescent' type=NoOp>

In [70]:
sess.run(  tf.global_variables_initializer( ))
for i in range(10):
    _,    loss_= sess.run(  (  train, loss) )
    print(loss_)

TypeError: Fetch argument 9.194634 has invalid type <class 'numpy.float32'>, must be a string or Tensor. (Can not convert a float32 into a Tensor or Operation.)

In [71]:
for i in range(100):
  _, loss_value = sess.run((train, loss))
  print(loss_value)

TypeError: Fetch argument 9.194634 has invalid type <class 'numpy.float32'>, must be a string or Tensor. (Can not convert a float32 into a Tensor or Operation.)

In [72]:
x = tf.constant([[1], [2], [3], [4]], dtype=tf.float32)
y_true = tf.constant([[0], [-1], [-2], [-3]], dtype=tf.float32)

linear_model = tf.layers.Dense(units=1)

y_pred = linear_model(x)
loss = tf.losses.mean_squared_error(labels=y_true, predictions=y_pred)

optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)

init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
for i in range(100):
  _, loss_value = sess.run((train, loss))
  print(loss_value)

print(sess.run(y_pred))

0.45629215
0.36071804
0.2941374
0.24767636
0.21517748
0.1923682
0.17628387
0.1648674
0.15669134
0.15076527
0.14640194
0.14312449
0.14060196
0.13860476
0.13697356
0.13559778
0.13440067
0.133329
0.13234583
0.13142547
0.13055013
0.12970746
0.12888883
0.12808828
0.12730172
0.1265262
0.12575968
0.12500085
0.1242487
0.12350249
0.12276177
0.122026175
0.12129547
0.12056952
0.11984811
0.119131155
0.118418634
0.11771048
0.11700657
0.116306946
0.11561149
0.114920214
0.11423309
0.11355011
0.11287122
0.11219634
0.111525536
0.11085872
0.11019592
0.10953708
0.10888216
0.10823118
0.10758406
0.10694085
0.10630146
0.105665915
0.10503415
0.10440618
0.10378195
0.103161454
0.10254466
0.10193156
0.10132214
0.10071631
0.10011414
0.09951559
0.09892061
0.09832918
0.097741276
0.09715688
0.09657601
0.095998585
0.09542465
0.09485411
0.09428698
0.093723275
0.093162924
0.09260588
0.09205222
0.09150186
0.090954795
0.09041099
0.08987042
0.08933309
0.08879898
0.08826807
0.08774034
0.08721577
0.086694285
0.08617595
0.0